name: Trigger auto deployment for adamaddison-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/adamaddison-container-AutoDeployTrigger-f5888867-c7e2-42d4-b4bb-4fd56d3fdb9a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ADAMADDISONCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ADAMADDISONCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ADAMADDISONCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: adamaddisoncontainer.azurecr.io
          registryUsername: ${{ secrets.ADAMADDISONCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ADAMADDISONCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: adamaddison-container
          resourceGroup: adamaddison-container-rg
          imageToBuild: adamaddisoncontainer.azurecr.io/adamaddison-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


